// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package stubs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SddtestccClient is the client API for Sddtestcc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SddtestccClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type sddtestccClient struct {
	cc grpc.ClientConnInterface
}

func NewSddtestccClient(cc grpc.ClientConnInterface) SddtestccClient {
	return &sddtestccClient{cc}
}

func (c *sddtestccClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/sddtestaa.sddtestbb.Sddtestcc/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SddtestccServer is the server API for Sddtestcc service.
// All implementations must embed UnimplementedSddtestccServer
// for forward compatibility
type SddtestccServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedSddtestccServer()
}

// UnimplementedSddtestccServer must be embedded to have forward compatible implementations.
type UnimplementedSddtestccServer struct {
}

func (UnimplementedSddtestccServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedSddtestccServer) mustEmbedUnimplementedSddtestccServer() {}

// UnsafeSddtestccServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SddtestccServer will
// result in compilation errors.
type UnsafeSddtestccServer interface {
	mustEmbedUnimplementedSddtestccServer()
}

func RegisterSddtestccServer(s grpc.ServiceRegistrar, srv SddtestccServer) {
	s.RegisterService(&Sddtestcc_ServiceDesc, srv)
}

func _Sddtestcc_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SddtestccServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sddtestaa.sddtestbb.Sddtestcc/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SddtestccServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sddtestcc_ServiceDesc is the grpc.ServiceDesc for Sddtestcc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sddtestcc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sddtestaa.sddtestbb.Sddtestcc",
	HandlerType: (*SddtestccServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Sddtestcc_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Sddtestcc.proto",
}
